/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "append.h"

int *
rpcinitappendserver_3_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    printf("%s\n", *argp);

    result = 5;

	return &result;
}

int *
rpcappend_3_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

    result = 2;

	return &result;
}
