/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "append.h"

int *
rpcinitappendserver_1_svc(append_init_params *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = 5;
    printf("%s\n", argp->host_verify);

	return &result;
}

int *
rpcappend_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;

    printf("[Remote] appending %c\n", *argp);
    result = -1;

	return &result;
}
