/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APPEND_H_RPCGEN
#define _APPEND_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define APPENDPROG 0x01310455
#define APPENDPROGVERS 3

#if defined(__STDC__) || defined(__cplusplus)
#define RPCInitAppendServer 1
extern  int * rpcinitappendserver_3(char **, CLIENT *);
extern  int * rpcinitappendserver_3_svc(char **, struct svc_req *);
#define RPCAppend 2
extern  int * rpcappend_3(char *, CLIENT *);
extern  int * rpcappend_3_svc(char *, struct svc_req *);
extern int appendprog_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPCInitAppendServer 1
extern  int * rpcinitappendserver_3();
extern  int * rpcinitappendserver_3_svc();
#define RPCAppend 2
extern  int * rpcappend_3();
extern  int * rpcappend_3_svc();
extern int appendprog_3_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APPEND_H_RPCGEN */
