/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "append.h"
#include "verify.h"

void appendprog_3(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * rpcinitappendserver_3_arg = "hello";
	int  *result_2;
	char  rpcappend_3_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, APPENDPROG, APPENDPROGVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpcinitappendserver_3(&rpcinitappendserver_3_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
        printf("append server init\n");
    } 
	result_2 = rpcappend_3(&rpcappend_3_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
        printf("append server append\n");
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void verifyprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * rpcinitverifyserver_1_arg = "supp duude";
	int  *result_2;
	int  rpcgetseg_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, VERIFYPROG, VERIFYPROGVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpcinitverifyserver_1(&rpcinitverifyserver_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
	    printf("ver server init\n");
	}
	result_2 = rpcgetseg_1(&rpcgetseg_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
	    printf("ver server get seg\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	appendprog_3 (host);
    verifyprog_1 (host);
exit (0);
}
