/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "verify.h"

int *
rpcinitverifyserver_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    printf("%s\n", *argp);
    result = 5;

	return &result;
}

int *
rpcgetseg_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = 4;

	return &result;
}
