/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VERIFY_H_RPCGEN
#define _VERIFY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct verify_init_params {
	int n;
	int l;
	int m;
};
typedef struct verify_init_params verify_init_params;

#define VERIFY_PROG 0x01327857
#define VERIFY_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define RPCInitVerifyServer 1
extern  int * rpcinitverifyserver_2(verify_init_params *, CLIENT *);
extern  int * rpcinitverifyserver_2_svc(verify_init_params *, struct svc_req *);
#define RPCGetSeg 2
extern  char ** rpcgetseg_2(int *, CLIENT *);
extern  char ** rpcgetseg_2_svc(int *, struct svc_req *);
#define RPCGetS 3
extern  char ** rpcgets_2(void *, CLIENT *);
extern  char ** rpcgets_2_svc(void *, struct svc_req *);
extern int verify_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPCInitVerifyServer 1
extern  int * rpcinitverifyserver_2();
extern  int * rpcinitverifyserver_2_svc();
#define RPCGetSeg 2
extern  char ** rpcgetseg_2();
extern  char ** rpcgetseg_2_svc();
#define RPCGetS 3
extern  char ** rpcgets_2();
extern  char ** rpcgets_2_svc();
extern int verify_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_verify_init_params (XDR *, verify_init_params*);

#else /* K&R C */
extern bool_t xdr_verify_init_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VERIFY_H_RPCGEN */
