/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "verify.h"

int *
rpcinitverifyserver_2_svc(verify_init_params *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = 5;

	return &result;
}

char **
rpcgetseg_2_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
    result = "later";

	return &result;
}

char **
rpcgets_2_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
    result = "hello";

	return &result;
}
