/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "verify.h"

bool_t
xdr_verify_init_params (XDR *xdrs, verify_init_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->l))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->m))
		 return FALSE;
	return TRUE;
}
