/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VERIFY_H_RPCGEN
#define _VERIFY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define VERIFYPROG 0x01327857
#define VERIFYPROGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPCInitVerifyServer 1
extern  int * rpcinitverifyserver_1(char **, CLIENT *);
extern  int * rpcinitverifyserver_1_svc(char **, struct svc_req *);
#define RPCGetSeg 2
extern  int * rpcgetseg_1(int *, CLIENT *);
extern  int * rpcgetseg_1_svc(int *, struct svc_req *);
extern int verifyprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPCInitVerifyServer 1
extern  int * rpcinitverifyserver_1();
extern  int * rpcinitverifyserver_1_svc();
#define RPCGetSeg 2
extern  int * rpcgetseg_1();
extern  int * rpcgetseg_1_svc();
extern int verifyprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VERIFY_H_RPCGEN */
